import { fmtTokens, pct } from '../format.js';

/** @param {string} s */
const esc = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/**
 * SVG polyline of context size per call, with compactions marked.
 * @param {import('../analyze.js').Analysis} a
 */
function profileSvg(a) {
  const w = 640;
  const h = 90;
  const max = Math.max(a.peakCtx, 1);
  const n = Math.max(a.profile.length - 1, 1);
  const pts = a.profile.map(
    (v, i) => `${((i / n) * w).toFixed(1)},${(h - (v / max) * (h - 6) - 3).toFixed(1)}`,
  );
  const marks = a.compactions
    .map(
      (i) =>
        `<line x1="${((i / n) * w).toFixed(1)}" x2="${((i / n) * w).toFixed(1)}" y1="0" y2="${h}" class="mark"/>`,
    )
    .join('');
  return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Context size per call, peak ${fmtTokens(a.peakCtx)}">${marks}<polyline points="${pts.join(' ')}" class="line"/></svg>`;
}

/**
 * Self-contained HTML report (no network requests, no scripts).
 * @param {import('../report.js').Report} report
 * @param {{top?: number}} [opts]
 */
export function renderHtml(report, opts = {}) {
  const top = opts.top ?? 10;
  const s = report.summary;
  const denom = Math.max(s.totalRead, s.toolRent + s.baselineRent + s.conversationRent, 1);
  const seg = (/** @type {number} */ v, /** @type {string} */ cls, /** @type {string} */ name) =>
    `<div class="seg ${cls}" style="flex:${Math.max(v, 0)}" title="${name}: ${pct(v, denom)}"><span>${name} ${pct(v, denom)}</span></div>`;

  const rows = report.bySignature
    .slice(0, top)
    .map(
      (g) =>
        `<tr><td><code>${esc(g.key)}</code></td><td>${g.calls}</td><td>${fmtTokens(g.tokens)}</td><td>${fmtTokens(g.rent)}</td>` +
        `<td><div class="meter"><i style="width:${Math.round((g.rent / Math.max(s.toolRent, 1)) * 100)}%"></i></div></td></tr>`,
    )
    .join('');
  const biggest = report.biggest
    .slice(0, 8)
    .map(
      (r) =>
        `<tr><td><code>${esc(r.label)}</code></td><td>${fmtTokens(r.tokens)}</td><td>${r.carried}</td><td>${fmtTokens(r.rent)}</td><td>${r.duplicate ? 'duplicate' : ''}</td></tr>`,
    )
    .join('');
  const advice = report.advice
    .map(
      (a) =>
        `<li><strong>${esc(a.title)}</strong><br>${esc(a.detail).replace(/`([^`]+)`/g, '<code>$1</code>')}</li>`,
    )
    .join('');
  const charts =
    report.sessions.length === 1
      ? `<h2>Context size per call</h2><div class="card">${profileSvg(report.sessions[0])}<p class="muted">peak ${fmtTokens(report.sessions[0].peakCtx)} tokens${report.sessions[0].compactions.length ? ', dashed lines mark compactions' : ''}</p></div>`
      : '';

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ctxrent report</title>
<style>
:root{--bg:#fff;--fg:#1b1f24;--muted:#656d76;--card:#f6f8fa;--line:#d0d7de;--tool:#cf222e;--base:#0969da;--conv:#8250df}
@media (prefers-color-scheme:dark){:root{--bg:#0d1117;--fg:#e6edf3;--muted:#8d96a0;--card:#161b22;--line:#30363d;--tool:#ff7b72;--base:#58a6ff;--conv:#bc8cff}}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,sans-serif}
main{max-width:860px;margin:0 auto;padding:24px 16px 48px}
h1{font-size:22px;margin:0 0 4px}h2{font-size:16px;margin:28px 0 8px}
.muted{color:var(--muted);font-size:13px}.banner{background:#fff8c5;color:#4d2d00;padding:8px 12px;border-radius:6px;margin:12px 0}
.card{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:12px}
.stack{display:flex;height:34px;border-radius:6px;overflow:hidden;font-size:12px;color:#fff}
.seg{display:flex;align-items:center;padding:0 8px;white-space:nowrap;overflow:hidden;min-width:0}
.seg.tool{background:var(--tool)}.seg.base{background:var(--base)}.seg.conv{background:var(--conv)}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--line);font-size:14px}
th{color:var(--muted);font-weight:500}td:nth-child(n+2){font-variant-numeric:tabular-nums}
.meter{background:var(--line);border-radius:4px;height:8px;width:120px}.meter i{display:block;height:8px;background:var(--tool);border-radius:4px}
code{font:13px ui-monospace,Menlo,monospace}svg{width:100%;height:auto}.line{fill:none;stroke:var(--base);stroke-width:2}.mark{stroke:var(--tool);stroke-dasharray:4 3}
ul{padding-left:20px}li{margin-bottom:8px}
</style>
</head>
<body>
<main>
<h1>ctxrent report</h1>
<p class="muted">${s.sessions} session(s) · ${s.turns} model calls · ${fmtTokens(s.totalRead)} tokens re-read · generated by ctxrent ${esc(report.version)}</p>
${report.demo ? '<div class="banner">Synthetic demo session: fabricated to show the report, not real usage data.</div>' : ''}
<h2>Where the re-read tokens came from</h2>
<div class="stack">${seg(s.toolRent, 'tool', 'tool outputs')}${seg(s.baselineRent, 'base', 'baseline')}${seg(s.conversationRent, 'conv', 'messages & other')}</div>
${charts}
<h2>Who pays the rent</h2>
<div class="card"><table><thead><tr><th>tool call</th><th>calls</th><th>size</th><th>rent</th><th>share</th></tr></thead><tbody>${rows}</tbody></table></div>
<h2>Most expensive single outputs</h2>
<div class="card"><table><thead><tr><th>output</th><th>size</th><th>calls carried</th><th>rent</th><th></th></tr></thead><tbody>${biggest}</tbody></table></div>
${advice ? `<h2>What would have helped</h2><ul>${advice}</ul>` : ''}
<p class="muted">Rent = estimated output size × number of model calls that re-read it before compaction or session end. Sizes are estimates at ${report.estimate.charsPerToken.toFixed(1)} chars/token.</p>
</main>
</body>
</html>
`;
}
