import { fmtTokens, pct } from '../format.js';

/** @param {string} s */
const cell = (s) => s.replace(/\|/g, '\\|').replace(/`/g, "'");

/**
 * A paste-able summary for issues, PRs and chat.
 * @param {import('../report.js').Report} report
 * @param {{top?: number}} [opts]
 */
export function renderMarkdown(report, opts = {}) {
  const top = opts.top ?? 8;
  const s = report.summary;
  const denom = Math.max(s.totalRead, 1);
  const lines = [
    '## ctxrent report',
    '',
    `${s.sessions} session(s), ${s.turns} model calls, **${fmtTokens(s.totalRead)}** tokens re-read` +
      (report.demo ? ' (synthetic demo data)' : ''),
    '',
    '| source | tokens re-read | share |',
    '| --- | ---: | ---: |',
    `| tool outputs | ${fmtTokens(s.toolRent)} | ${pct(s.toolRent, denom)} |`,
    `| fixed baseline | ${fmtTokens(s.baselineRent)} | ${pct(s.baselineRent, denom)} |`,
    `| messages, thinking & other | ${fmtTokens(s.conversationRent)} | ${pct(s.conversationRent, denom)} |`,
    '',
    '### Who pays the rent',
    '',
    '| tool call | calls | total size | rent | share of tool rent |',
    '| --- | ---: | ---: | ---: | ---: |',
    ...report.bySignature
      .slice(0, top)
      .map(
        (g) =>
          `| \`${cell(g.key)}\` | ${g.calls} | ${fmtTokens(g.tokens)} | ${fmtTokens(g.rent)} | ${pct(g.rent, s.toolRent)} |`,
      ),
    '',
  ];
  if (report.advice.length > 0) {
    lines.push('### What would have helped', '');
    for (const a of report.advice) lines.push(`- **${a.title}**: ${a.detail}`);
    lines.push('');
  }
  lines.push(
    `_Sizes are estimates (${report.estimate.charsPerToken.toFixed(1)} chars/token). Generated by ctxrent ${report.version}._`,
    '',
  );
  return lines.join('\n');
}
